/dev/sda -a -o on -S on -n standby,8 -s (S/../.././02|L/../../6/03) -m root@idle-r.ru
/dev/sdb -a -o on -S on -n standby,8 -s (S/../.././02|L/../../6/03) -m root@idle-r.ru
/dev/sdc -a -o on -S on -n standby,8 -s (S/../.././02|L/../../6/03) -m root@idle-r.ru
/dev/sdd -a -o on -S on -n standby,8 -s (S/../.././02|L/../../6/03) -m root@idle-r.ru
